// Expo app configuration (CNG / prebuild). Native crypto (M1) rules out Expo Go,
// so the app runs through a custom dev-client. The ios/ and android/ folders are
// generated by `expo prebuild` and stay out of git — this file is the source of
// truth for native config.
/** @type {import('expo/config').ExpoConfig} */
const config = {
  name: "Wharf",
  slug: "wharf-mobile",
  version: "0.1.0",
  orientation: "portrait",
  icon: "./assets/images/icon.png",
  scheme: "wharf",
  userInterfaceStyle: "dark",
  // New Architecture is the only mode in SDK 57 (Expo Go dropped legacy arch), so
  // there is no flag to set — it is on for every prebuild.
  ios: {
    supportsTablet: false,
    bundleIdentifier: "de.jannekeipert.wharf",
    // Declares the app uses only exempt/standard encryption (answered at the EAS
    // prompt) so App Store Connect skips the annual self-classification report.
    infoPlist: {
      ITSAppUsesNonExemptEncryption: false,
    },
  },
  android: {
    package: "de.jannekeipert.wharf",
    adaptiveIcon: {
      backgroundColor: "#0A0E13",
      foregroundImage: "./assets/images/android-icon-foreground.png",
      monochromeImage: "./assets/images/android-icon-monochrome.png",
    },
    predictiveBackGestureEnabled: false,
  },
  plugins: [
    "expo-router",
    "expo-dev-client",
    // react-native-libsodium ships an Expo config plugin (app.plugin.js) that
    // wires the JSI native build. The wharf-argon2 local module (modules/) is
    // auto-linked by expo-modules-autolinking and needs no plugin entry.
    "react-native-libsodium",
    // M2 native modules: keychain-backed token/DEK storage, the biometric
    // prompt (with the iOS Face ID usage string), and the OAuth system browser.
    "expo-secure-store",
    "expo-web-browser",
    [
      "expo-local-authentication",
      {
        faceIDPermission: "Wharf uses Face ID to unlock your encrypted vault.",
      },
    ],
    [
      "expo-splash-screen",
      {
        backgroundColor: "#0A0E13",
        image: "./assets/images/splash-icon.png",
        imageWidth: 76,
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
  },
  // EAS Update (expo-updates): OTA JS delivery, keyed to this EAS project. The
  // runtime version follows the app version, so a native change (new appVersion)
  // starts a fresh update lineage.
  updates: {
    url: "https://u.expo.dev/47bc9fd7-7935-4077-b3e2-e4f66441751f",
  },
  runtimeVersion: {
    policy: "appVersion",
  },
  owner: "janne6565",
  extra: {
    eas: {
      projectId: "47bc9fd7-7935-4077-b3e2-e4f66441751f",
    },
  },
};

module.exports = config;
