// Objective-C API for talking to github.com/Janne6565/wharf-mobile/sshengine Go package.
//   gobind -lang=objc github.com/Janne6565/wharf-mobile/sshengine
//
// File is generated by gobind. Do not edit.

#ifndef __Sshengine_H__
#define __Sshengine_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class SshengineEngine;
@protocol SshengineCallbacks;
@class SshengineCallbacks;

@protocol SshengineCallbacks <NSObject>
/**
 * OnClosed fires exactly once per established session. errMsg is "" on a
clean end (clean remote exit or a caller-initiated Close); otherwise it
carries the failure reason (network drop, keepalive loss, non-zero exit).
 */
- (void)onClosed:(NSString* _Nullable)sessionID errMsg:(NSString* _Nullable)errMsg;
/**
 * OnData delivers merged remote stdout+stderr for a session. The []byte is
owned by the callee (a fresh copy per call).
 */
- (void)onData:(NSString* _Nullable)sessionID data:(NSData* _Nullable)data;
/**
 * OnHostKeyPrompt asks the user to trust an unknown host key (TOFU). Answer
with ResolveHostKeyPrompt(promptID, accept). A CHANGED key never prompts —
it fails Connect immediately with a host_key_changed error.
 */
- (void)onHostKeyPrompt:(NSString* _Nullable)promptID sessionID:(NSString* _Nullable)sessionID host:(NSString* _Nullable)host keyType:(NSString* _Nullable)keyType fingerprint:(NSString* _Nullable)fingerprint;
/**
 * OnSecretPrompt asks the user for a secret. kind is one of:
  "password"       first password ask, no stored password was tried
  "password_retry" a previous password (stored or typed) was rejected
  "ki"             a keyboard-interactive question from the server
echo reports whether the server allows the input to be shown. Answer with
ResolveSecretPrompt(promptID, secret); pass nil to cancel authentication.
 */
- (void)onSecretPrompt:(NSString* _Nullable)promptID sessionID:(NSString* _Nullable)sessionID kind:(NSString* _Nullable)kind prompt:(NSString* _Nullable)prompt echo:(BOOL)echo;
@end

/**
 * Engine owns all live sessions, the known-hosts policy, and the pending
prompt registry. Its methods are safe for concurrent use from native
threads and from the engine's own goroutines.
 */
@interface SshengineEngine : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewEngine creates an engine verifying host keys against knownHostsPath
(created 0600 with a 0700 parent on first accepted key) and delivering
events to cb.
 */
- (nullable instancetype)init:(NSString* _Nullable)knownHostsPath cb:(id<SshengineCallbacks> _Nullable)cb;
/**
 * CancelConnect aborts a Connect still in progress for sessionID (cancels its
context, unblocking a pending host-key/secret prompt, dial, or handshake).
It is a no-op once the shell is established or if there is no such attempt.
 */
- (void)cancelConnect:(NSString* _Nullable)sessionID;
/**
 * Close terminates a session. It is idempotent and safe from any thread; the
resulting OnClosed reports a clean end ("").
 */
- (void)close:(NSString* _Nullable)sessionID;
/**
 * CloseAll terminates every live session.
 */
- (void)closeAll;
/**
 * Connect blocks until the interactive shell is established or the attempt
fails, so the native side must call it on a background thread. sessionID is
caller-supplied and must be unique per attempt; it keys every later call and
every callback for this session.

storedPassword "" means none. A non-empty stored password is replayed
silently on the first attempt; if the server rejects it, prompting continues
via OnSecretPrompt with kind "password_retry" (total 1 silent + 3 prompted,
versus 3 prompted when nothing is stored).

timeoutMs bounds TCP dial + handshake + auth as a whole; <= 0 means no
deadline (the attempt can still be aborted with CancelConnect). Once the
shell is up the only watchdog is the 30s keepalive loop.

A non-nil error's message is prefixed with a stable, parseable code:
host_key_changed, host_key_rejected, auth_failed, canceled, timeout,
network, or unknown, followed by ": " and detail.
 */
- (BOOL)connect:(NSString* _Nullable)sessionID host:(NSString* _Nullable)host port:(long)port user:(NSString* _Nullable)user storedPassword:(NSString* _Nullable)storedPassword termType:(NSString* _Nullable)termType cols:(long)cols rows:(long)rows timeoutMs:(long)timeoutMs error:(NSError* _Nullable* _Nullable)error;
/**
 * Resize updates the remote PTY window to cols x rows. It errors if the
session is unknown or already closed.
 */
- (BOOL)resize:(NSString* _Nullable)sessionID cols:(long)cols rows:(long)rows error:(NSError* _Nullable* _Nullable)error;
/**
 * ResolveHostKeyPrompt answers an OnHostKeyPrompt. accept=true trusts and
persists the key; false aborts the connection. Unknown/expired promptIDs are
silently ignored.
 */
- (void)resolveHostKeyPrompt:(NSString* _Nullable)promptID accept:(BOOL)accept;
/**
 * ResolveSecretPrompt answers an OnSecretPrompt with secret; nil means the user
cancelled authentication. Unknown/expired promptIDs are silently ignored.
 */
- (void)resolveSecretPrompt:(NSString* _Nullable)promptID secret:(NSData* _Nullable)secret;
/**
 * Snapshot returns a copy of the session's ring buffer (most recent output, up
to 256 KiB) in write order, for replay after reattaching. It returns nil for
an unknown session.
 */
- (NSData* _Nullable)snapshot:(NSString* _Nullable)sessionID;
/**
 * Write forwards keystrokes to the session's remote stdin. It errors if the
session is unknown or already closed.
 */
- (BOOL)write:(NSString* _Nullable)sessionID data:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
@end

@interface Sshengine : NSObject
/**
 * ErrAuthFailed wraps the handshake error when every auth method was rejected.
 */
+ (NSError* _Nullable) errAuthFailed;
+ (void) setErrAuthFailed:(NSError* _Nullable)v;

/**
 * ErrCanceled: a prompt was cancelled (nil secret) or the attempt was
aborted (CancelConnect / no callbacks wired).
 */
+ (NSError* _Nullable) errCanceled;
+ (void) setErrCanceled:(NSError* _Nullable)v;

/**
 * ErrHostKeyChanged: the server presented a host key differing from the one
in known_hosts. Never prompted — treated as a hard failure (possible MITM).
 */
+ (NSError* _Nullable) errHostKeyChanged;
+ (void) setErrHostKeyChanged:(NSError* _Nullable)v;

/**
 * ErrHostKeyRejected: the user declined to trust an unknown host key.
 */
+ (NSError* _Nullable) errHostKeyRejected;
+ (void) setErrHostKeyRejected:(NSError* _Nullable)v;

@end

/**
 * NewEngine creates an engine verifying host keys against knownHostsPath
(created 0600 with a 0700 parent on first accepted key) and delivering
events to cb.
 */
FOUNDATION_EXPORT SshengineEngine* _Nullable SshengineNewEngine(NSString* _Nullable knownHostsPath, id<SshengineCallbacks> _Nullable cb);

/**
 * Probe TCP-dials host:port and reports reachability for the host-list status
dot. It returns the dial RTT in milliseconds (minimum 1) on success, or -1
when the dial fails (refused, unreachable, or timed out). port <= 0 defaults
to 22; timeoutMs <= 0 defaults to 3000. Classification (online vs degraded)
is done by the JS side so the threshold lives with the UI.

This is a stateless package-level function (gomobile binds it as
SshengineProbe): it needs no engine instance and is safe to call with no
session. It mirrors wharf-tui's probe.Dial — a single net.DialTimeout with
the connection closed immediately on success.
 */
FOUNDATION_EXPORT long SshengineProbe(NSString* _Nullable host, long port, long timeoutMs);

@class SshengineCallbacks;

/**
 * Callbacks is the native-side listener. Implementations are provided by the
Swift/Kotlin Expo module. See the package doc for the (load-bearing)
threading contract: every method here runs on an engine goroutine and must
return quickly without blocking.
 */
@interface SshengineCallbacks : NSObject <goSeqRefInterface, SshengineCallbacks> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * OnClosed fires exactly once per established session. errMsg is "" on a
clean end (clean remote exit or a caller-initiated Close); otherwise it
carries the failure reason (network drop, keepalive loss, non-zero exit).
 */
- (void)onClosed:(NSString* _Nullable)sessionID errMsg:(NSString* _Nullable)errMsg;
/**
 * OnData delivers merged remote stdout+stderr for a session. The []byte is
owned by the callee (a fresh copy per call).
 */
- (void)onData:(NSString* _Nullable)sessionID data:(NSData* _Nullable)data;
/**
 * OnHostKeyPrompt asks the user to trust an unknown host key (TOFU). Answer
with ResolveHostKeyPrompt(promptID, accept). A CHANGED key never prompts —
it fails Connect immediately with a host_key_changed error.
 */
- (void)onHostKeyPrompt:(NSString* _Nullable)promptID sessionID:(NSString* _Nullable)sessionID host:(NSString* _Nullable)host keyType:(NSString* _Nullable)keyType fingerprint:(NSString* _Nullable)fingerprint;
/**
 * OnSecretPrompt asks the user for a secret. kind is one of:
  "password"       first password ask, no stored password was tried
  "password_retry" a previous password (stored or typed) was rejected
  "ki"             a keyboard-interactive question from the server
echo reports whether the server allows the input to be shown. Answer with
ResolveSecretPrompt(promptID, secret); pass nil to cancel authentication.
 */
- (void)onSecretPrompt:(NSString* _Nullable)promptID sessionID:(NSString* _Nullable)sessionID kind:(NSString* _Nullable)kind prompt:(NSString* _Nullable)prompt echo:(BOOL)echo;
@end

#endif
