
// Objective-C API for talking to the following Go packages
//
//	github.com/Janne6565/wharf-mobile/sshengine
//
// File is generated by gomobile bind. Do not edit.
#ifndef __WharfSshEngine_FRAMEWORK_H__
#define __WharfSshEngine_FRAMEWORK_H__

#include "Sshengine.objc.h"
#include "Universe.objc.h"

#endif
